language_comment_syntax = {
    "c44": {"line": "//", "block": ("/*", "*/")},
    "csharpe107": {"line": "//", "block": ("/*", "*/"), "doc": "///"},
    "cpp92": {"line": "//", "block": ("/*", "*/")},
    "Dart33": {"line": "//", "block": ("/*", "*/")},
    "Elixir15": {"line": "#"},
    "Erlang23": {"line": "%"},
    "Fortran103": {"line": "!"},
    "Go25": {"line": "//", "block": ("/*", "*/")},
    "Java67": {"line": "//", "block": ("/*", "*/")},
    "JS59": {"line": "//", "block": ("/*", "*/")},
    "Kotlin79": {"line": "//", "block": ("/*", "*/")},
    "Lua22": {"line": "--", "block": ("--[[", "]]")},
    "MATLAB20": {"line": "%"},
    "Objective_C85": {"line": "//", "block": ("/*", "*/")},
    "PHP69": {"line": "// or #", "block": ("/*", "*/")},
    "Python38": {"line": "#"},
    "R21": {"line": "#"},
    "Ruby41": {"line": "#", "block": ("=begin", "=end")},
    "Rust53": {"line": "//", "block": ("/*", "*/"), "doc": "///"},
    "Scala40": {"line": "//", "block": ("/*", "*/")},
    "Swift97": {"line": "//", "block": ("/*", "*/")},
}
